<div class="checkout-success">
    <div class="success-logo" style="margin-bottom: 15px;">
        <img src="<?= $this->getViewFileUrl('Boodil_Payment::images/boodil.svg'); ?>" alt="<?= __('boodil') ?>" />
    </div>
    <h1 class="page-title">
        <span class="base"><?= __("Payment Successful with Boodil"); ?></span>
    </h1>
    <?php if($block->getRequest()->getParam('mobile')) :?>
        <p><?= __("Your transaction was completed on your mobile device, you can see your order confirmation there."); ?></p>
    <?php else :?>
        <p><?= __("Your transaction was completed in another window, you can see your order confirmation there."); ?></p>
    <?php endif;?>       
</div>
<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {

        setTimeout(function () {
            var sections = ['cart'];
            customerData.get('cart').subscribe(function (cart) {
                if (cart.summary_count > 0) {
                    customerData.invalidate(sections);
                    customerData.reload(sections, true);
                }
            })

        }, 1)
    });
</script>
