<div class="checkout-success">
    <div class="success-logo">
        <img src="<?= $this->getViewFileUrl('Boodil_Payment::images/boodil.svg'); ?>" alt="<?= __('boodil') ?>" />
    </div>
    <h1 class="page-title">
        <span class="base"><?= __("Payment Successful with Boodil"); ?></span>
    </h1>
    <?php if($block->getRequest()->getParam('mobile')) :?>
        <p><?= __("Your transaction was completed on your mobile device, you can see your order confirmation there."); ?></p>
    <?php else :?>
        <p><?= __("Your transaction was completed in another window, you can see your order confirmation there."); ?></p>
    <?php endif;?>       
</div>
